### ISSUE TITLE
run one order id

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/MetOfficeDataHub#20]
## Detailed Description
Add option to add order id, (or order ids) rather than serarching for all the order ids

## Context
Would be good to just run app on one order id. People many have serval orders under one account. 

## Task Breakdown

- [x] Add option to pass ORDER_IDS to MetOfficeDataHub -> https://github.com/openclimatefix/MetOfficeDataHub/pull/49
- [x] Add to aws secret 
  - [x] [dev](https://eu-west-1.console.aws.amazon.com/secretsmanager/secret?name=development%2Fconsumer%2Fnwp&region=eu-west-1)
  - [x] prod
- [x] Add order id into terraform consumer task
  - [x] dev -> https://github.com/openclimatefix/nowcasting_infrastructure/pull/148
  - [x] prod -> https://github.com/openclimatefix/nowcasting_infrastructure/pull/149
- [x] Plan and apply tf change
  - [x] dev -> https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_development-eu-west-1/runs/run-MW3rRm9Byx6rQkT9
  - [x] prod -> https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_production-eu-west-1/runs/run-rRXTzkzTxR8y6HKi
- [x] Update NWP container version in tf
  - [x] dev -> https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_development-eu-west-1/runs/run-vW6qmrayyNjSgWPN
  - [x] prod -> https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_production-eu-west-1/runs/run-tcAfWUnuWzzqWmgu

**Comment by devsjc** [comment]
@peterdudfield For this, we've two behaviour options that could occur when no order ID's are manually supplied as input:
1. Download all latest files from all order IDs (current behaviour)
2. Download nothing
Is one or the other preferable?

**Comment by devsjc** [comment]
See #49

**Comment by peterdudfield** [comment]
> @peterdudfield For this, we've two behaviour options that could occur when no order ID's are manually supplied as input:
> 
> 1. Download all latest files from all order IDs (current behaviour)
> 2. Download nothing
> 
> Is one or the other preferable?

Hmm, I'm not sure now. Maybe 1., means there are not breaking changes. But 2. ensures better protection. Lets do 2, and we can always role back if there is a problem

**Comment by devsjc** [comment]
Alright, I'll make that change.

**Comment by peterdudfield** [comment]
Ive added (small) details for tasks 2. (AWS secret) and 3. (terraform)

**Comment by devsjc** [comment]
Secret updated in dev

**Comment by devsjc** [comment]
Adding secret to terraform https://github.com/openclimatefix/nowcasting_infrastructure/pull/148

**Comment by devsjc** [comment]
### Dev

Applied update to NWP version

**Comment by devsjc** [comment]
Looks like it's worked in dev, so far as I can tell anyway. Is there a process beyond that for being comfortable with pushing through to live?

**Comment by peterdudfield** [comment]
> Looks like it's worked in dev, so far as I can tell anyway. Is there a process beyond that for being comfortable with pushing through to live?

No really. Trying to keep things as stream line as possible. Is there are reason we shouldnt push this to live. Perhaps waiting 1 day is reasonable, and if you did it yesterday then should be fine today on live.

**Comment by devsjc** [comment]
If you've not seen anything break in dev since yesterday there's no reason this can't go through in my book! It looked to be working from my perspective, but I wouldn't necessarily trust my judgement on that all the way for the moment since I've only just started: could be something I don't know about somewhere that isn't working...!

**Comment by devsjc** [comment]
### Prod

Merge request for pasing secret to container in terraform https://github.com/openclimatefix/nowcasting_infrastructure/pull/149
- [] Merged
- [] [Applied]()

**Comment by devsjc** [comment]
### Prod

- [x] Order ID added in AWS secret manager

**Comment by devsjc** [comment]
### Prod

Update to NWP version number terraform variable 
- [x] [Applied](https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_production-eu-west-1/runs/run-tcAfWUnuWzzqWmgu)
